#!/bin/bash

#
set -o errexit
#
shopt -s expand_aliases

# BEGIN _functions

# @info:    Prints the ascii logo
asciiLogo ()
{
  echo
  echo " .----------------.  .----------------.  .----------------.  .----------------. 	";
  echo "| .--------------. || .--------------. || .--------------. || .--------------. |	";
  echo "| | ____    ____ | || |      __      | || |    ______    | || |  _________   | |	";
  echo "| ||_   \  /   _|| || |     /  \     | || |  .' ___  |   | || | |_   ___  |  | |	";
  echo "| |  |   \/   |  | || |    / /\ \    | || | / .'   \_|   | || |   | |_  \_|  | |	";
  echo "| |  | |\  /| |  | || |   / ____ \   | || | | |    ____  | || |   |  _|  _   | |	";
  echo "| | _| |_\/_| |_ | || | _/ /    \ \_ | || | \ \`.___]  _| | || |  _| |___/ |  | |	";
  echo "| ||_____||_____|| || ||____|  |____|| || |  \`._____.'   | || | |_________|  | |	";
  echo "| |              | || |              | || |              | || |              | |	";
  echo "| '--------------' || '--------------' || '--------------' || '--------------' |	";
  echo " '----------------'  '----------------'  '----------------'  '----------------' 	";
  echo
}

# @info:    Prints the usage
usage ()
{
  asciiLogo

  cat <<EOF
Usage: $0 <command> [options]

Examples:

  $(green "mage alias ")         Setup the alias.

  $(green "mage sf ")            Run php bin/console through Docker.

  $(green "mage composer ")      Run composer through Docker.

EOF
  exit 0
}

parseCli()
{
  [ "$#" -ge 1 ] || usage

  command=$1

  case "$command" in
    "alias") cmdSetupAlias
    ;;
    "sf") cmdSf $@
    ;;
    "composer") cmdComposer $@
    ;;
    "comp") cmdComposer $@
    ;;
#    "make:controller") cmdMakeController $@
#    ;;
#    "make:command") cmdMakeCommand $@
#    ;;
#    "make:entity") cmdMakeEntity $@
#    ;;
    *) UnknownArgument $1
    ;;
  esac

}

#cmdMakeController()
#{
#  namespaceController='App\UI\Web'
#
#  makeCustom ${namespaceController} 'controller' '--no-template'
#}
#
#cmdMakeCommand()
#{
#  makeCustom 'App\UI\Cli' 'command'
#}
#
#cmdMakeEntity()
#{
#  makeCustom 'App\Domain' 'entity' $2
#}

cmdSf()
{
  docker-compose exec php sh -lc "./bin/console $2"
}

cmdComposer()
{
  docker-compose exec php sh -lc "composer $2 $3 $4"
}

cmdSetupAlias()
{
  if grep -q "mage=" ~/.aliases; then
   echoWarn "Alias 'mage' already added."
   return
  fi

  dir=$(pwd)

  if [ ! -f ~/.aliases ]; then
    if [ -f ~/.zshrc ]; then
      echo "source ~/.aliases" >> ~/.zshrc
    elif [ -f ~/.zshrc ]; then
      echo "source ~/.aliases" >> ~/.bashrc
    else
      echoError "Neither .bashrc or .zshrc found."
    fi
    touch ~/.aliases
  fi

  echo "alias mage=\"${dir}/mage\"" >> ~/.aliases

  exec $SHELL

  echoSuccess "'mage' shortcut successfully added to ~/.aliases."

}

# PRIVATE METHODS
#makeCustom()
#{
#  docker-compose exec php sh -lc "MAKER_NAMESPACE='${1}' ./bin/console make:${2} ${3}"
#}


green ()
{
  printf "\033[1;32m$1\033[0m\n"
}

# @info:    Prints success messages
# @args:    success-message
echoSuccess ()
{
  printf "\033[1;32m[MAGE] \033[0m$1\n"
}

# @info:    Prints check messages
# @args:    success-message
echoInfo ()
{
  printf "\033[1;34m[MAGE-INFO] \033[0m$1\n"
}

# @info:    Prints error messages
# @args:    error-message
echoError ()
{
  printf "\033[1;31m[MAGE-FAILED] \033[0m$1\n"
}

# @info:    Prints warning messages
# @args:    warning-message
echoWarn ()
{
  printf "\033[1;33m[MAGE-WARNING] \033[0m$1\n"
}

parseCli "$@"